config/routes.rb
Rails.application.routes.draw do
  resources :dogs, :users, :welcome, :sessions, :walks

  resources :users do
    resources :dogs, :walks
  end

  resources :dogs do
    resources :walks
  end

  # root to: "photos#index"
resources :photos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  patch '/users/:id' => 'user#udpate', :as => :update_user
  get '/update_dogs' => 'walks#update', :as => :update_dogs
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
  get '/auth/github/callback' => 'sessions#create'
  get 'dogs/:id/schedule' => 'dogs#schedule', :as => :schedule
  post "dogs/create" => 'dogs#create', :as => :create_dog
  get '/walks/:id/participants' => 'walks#participants', :as => :participants

  match '/login' => 'sessions#new', via: [:get, :post]
  match '/auth/user/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/user/register', to: 'sessions#create', via: [:get, :post]
end

app/models/dog.rb
class Dog < ApplicationRecord
  validates :name, :breed, :age, presence: true

  belongs_to :user
  has_many :dogs_walks
  has_many :walks, through: :dogs_walks

    #Mounts paperclip image
  has_attached_file :image, :styles => { :large => "900>", :medium => width = "600>", :small => width = "300>", :thumb => "100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :dogs_walks

  def current_dog_walk(walk)
    DogsWalk.find_by(dog_id: self.id, walk_id:  walk.id)
  end

  def self.most_walks
    @walk_count = DogsWalk.group("dog_id").order("count_dog_id desc").count("dog_id")
    @dog = Dog.find(@walk_count.keys[0])
  end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def new
    @dog = Dog.new
  end

  def index
    @dogs = Dog.all
  end

  def create
    byebug
    @dog = current_user.dogs.build(dog_params)
    @dog.save
    if @dog.valid?
      render json: @dog, status: 201
    else
      redirect_to new_dog_path
    end
  end

  def update
    @dog = Dog.find(params[:id])
  end

  def show
    @dog = Dog.find(params[:id])
    @walks = @dog.walks
    render :json => {:dog => @dog, :walks=> @walks}
    # respond_to do |format|
    #   format.html
    #   format.json {render json: @dog, include: [:walks]} - use to add walks to dog show on user page
    # end
  end

  def schedule
    @dog = Dog.find(params[:id])
    @walks = @dog.walks
    render json: @walks, status: 201
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed, :age, :user_id, :notes)
  end

end

app/views/dogs/_form.html.erb
<div class="returned_new_dog">

</div>

<%= form_for :dog, url: '/dogs/create', :html => {class: "new_dog"} do |f| %>

  <div class="new_dog_form">
    Name: <%= f.text_field :name %><br>
    Breed: <%= f.text_field :breed %><br>
    Age: <%= f.number_field :age %><br>
    Notes: <br><%= f.text_area :notes , cols: "30", rows: "10" %><br><br>

    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/_links.html.erb
<p><%= button_to "Go to your Page", user_path(current_user.id), {method: :get} %></p>
<p><%= button_to "Add a Dog", new_dog_path, {method: :get} %></p>
<p><%= button_to "Book a Walk", walks_path, {method: :get} %></p><br>

app/views/dogs/_show.html.erb
<div class="dog">

</div>

  <h2><%= @dogs[@index].name %></h2>
  <p>Breed: <%= @dogs[@index].breed %></p>
  <p>Age: <%= @dogs[@index].age %></p>
  <p>Notes: <br><%= @dogs[@index].notes %><br><br>

app/views/dogs/_walks_links.html.erb
<p>
<%= link_to 'See Scheduled Walks', schedule_path(@dog), :class => 'load_walks' %>
</p>
<div class="walks">

</div>

app/views/dogs/confirm_walk.html.erb
<%= render partial: 'form', locals: { walk: @walk } %><br>
<%= render partial: 'show_dogs', locals: { walk: @walk } %><br><br>
<%= render partial: 'update_dogs', locals: { walk: @walk} %><br><br><br><br>


<p><%= button_to "Go to your Page", user_path(current_user.id), {method: :get} %></p>
<p><%= button_to "Confirm", walks_path, {method: :get} %></p><br>

app/views/dogs/edit.html.erb
<%= render partial: 'form', locals: { owner: @owner } %>

<%= render partial: 'links' %>

app/views/dogs/index.html.erb
<% @dogs.each do |d| %>
  <h3><%= link_to "#{d.name}", dog_path(d.id)%></h3><br>
<% end %>

app/views/dogs/new.html.erb
<%= render partial: 'form', locals: { user: @user, dog: @dog, dogs: @dogs } %>

<%= render partial: 'links' %>

app/views/dogs/show.html.erb
<%= render partial: 'show' %>

<%= render partial: 'walks_links' %>

<%= render partial: 'links' %>