config/routes.rb
Rails.application.routes.draw do
  resources :dogs, :users, :welcome, :sessions, :walks

  resources :users do
    resources :dogs, :walks
  end

  resources :dogs do
    resources :walks
  end

  # root to: "photos#index"
resources :photos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  patch '/users/:id' => 'user#udpate', :as => :update_user
  get '/update_dogs' => 'walks#update', :as => :update_dogs
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
  get '/auth/github/callback' => 'sessions#create'
  get 'dogs/:id/schedule' => 'dogs#schedule', :as => :schedule
  post "dogs/create" => 'dogs#create', :as => :create_dog
  get '/walks/:id/participants' => 'walks#participants', :as => :participants

  match '/login' => 'sessions#new', via: [:get, :post]
  match '/auth/user/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/user/register', to: 'sessions#create', via: [:get, :post]
end

app/models/user.rb
class User< OmniAuth::Identity::Models::ActiveRecord
  has_secure_password
  validates_presence_of :name
  validates_uniqueness_of :email

      #Mounts paperclip image
  has_attached_file :image, :styles => { :large => "900>", :medium => width = "600>", :small => width = "300>", :thumb => "100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :dogs
  has_many :walks, through: :dogs


  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) ||create_with_omniauth(auth)
  end

  require 'securerandom'

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.password = SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @dogs = Dog.where(user_id: @user.id)
  end

  def update
    @user = User.find(params[:id])
    @user.update(name: params[:name], email: params[:email])

    redirect_to edit_user_path(@user), notice: "Update Successful"
  end


  def edit
    # byebug
    @user = User.find(params[:id].to_i)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_photo.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <% if @photo %>
    <% if @photo.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
        </h2>
        <ul>
          <% @photo.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <%end%>

  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/_addphoto.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <% if @photo %>
    <% if @photo.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
        </h2>
        <ul>
          <% @photo.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
        </ul>
      </div>
    <% end %>
  <%end%>

  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  <!-- </div>

  <div class="form-group"> -->
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
        <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/_edit_photo.html.erb
<div class="media-left">
  <!-- Renders image -->
  <%= link_to image_tag(user.image.url(:medium), class: 'media-object'), user.image.url, target: '_blank' %>
  <!-- Button to delete image -->
  <%= link_to 'Remove', user_path(image), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/users/_edit_user_form.html.erb
<%= form_for user do %>
  <% if @user && @user.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @user.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @user.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Update" %></div>
<% end %>

app/views/users/_form.html.erb
<%= button_to "Edit", edit_user_path(@user), :method => "get" %>add/change photo or update profile.<br /><br />

app/views/users/_scheduled_walks.html.erb
<%= "Currently Scheduled Walks:" %><br />
<% walks = @user.walks.uniq {|w| w.id } %>
<% walks.each do |w| %>
  <%= link_to "#{w.date} @ #{w.time} with #{w.walker_name}", user_walk_path(@user.id, w.id) %><br>
  <%= safe_join(w.dogs.map { |d| d.name}, ', ') %><br /><br /><br />
<%end%><br />

<%= button_to "Schedule a Walk", walks_path, {method: :get} %><br />

app/views/users/_show_photo.html.erb
<!-- <div class="page-header"><h1>Photos</h1></div> -->

<div class="media">
  <% if @user.image_file_name != nil %>

    <div class="media-left">
      <!-- Renders image -->
      <%= link_to image_tag(@user.image.url(:medium), class: 'media-object'), @user.image.url, target: '_blank' %>
      <!-- Button to delete image -->
      <%= link_to 'Remove', photo_path(@user.image), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
    <% end %>
</div>

app/views/users/_user_form.html.erb
<%= form_tag "/auth/user/register" do %>
  <% if @user && @user.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag :name %><br>
    <%= text_field_tag :name, @user.try(:name) %>
  </div>
  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @user.try(:email) %>
  </div>
  <div class="field">
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag :password_confirmation %>
  </div>
  <div class="actions"><%= submit_tag "Register" %></div>
<% end %>

app/views/users/_users_dogs.html.erb
  Your currently registered dogs:<br />

<% if @dogs %>
  <% @dogs.each do |d| %>
    <%= link_to d.name, user_dog_path(@user.id, d.id), :class => 'show_dog'%><br />
  <% end %>
<% end %><br />


<%= button_to "Add a new dog", new_dog_path, {method: :get} %><br />

app/views/users/edit.html.erb
<div class="row">
  <div class="column">
    <% if notice.present? %>
      <h2><%= notice %></h2>
    <% end %>
    <%= render partial: 'edit_user_form', locals: { user: @user } %>
  </div>

  <div class="column">
    <p>
      Add/Change photo: <%= render partial: 'add_photo', locals: { user: @user, image: @image} %>
    </p>
  </div>
</div>

app/views/users/new.html.erb
<div class="column">
  <%= render partial: 'user_form', locals: { user: @user } %>
</div>

app/views/users/show.html.erb
<h1>Hello, <%= @user.name %>!</h1>
<div class="row">
  <div class="column3">
    <%= render partial: 'form', locals: { user: @user, dog: @dog, dogs: @dogs } %>

    <%= render partial: 'show_photo', locals: { user: @user} %>
  </div>
  <div class="column3">

          <%= render partial: 'scheduled_walks', locals: { user: @user, dog: @dog, dogs: @dogs } %>
  </div>
  <div class="column3">
        <%= render partial: 'users_dogs', locals: { user: @user, dog: @dog, dogs: @dogs } %>
      <div class="column3-1">
        <div class="dog">
        </div>
      </div>
      <div class="column3-2">
        <%= render partial: 'show_photo', locals: { user: @user, dog: @dog, dogs: @dogs } %>
      </div>
    </div>
  </div>
</div>