config/routes.rb
Rails.application.routes.draw do
  resources :dogs, :users, :welcome, :sessions, :walks

  resources :users do
    resources :dogs, :walks
  end

  resources :dogs do
    resources :walks
  end

  # root to: "photos#index"
resources :photos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  patch '/users/:id' => 'user#udpate', :as => :update_user
  get '/update_dogs' => 'walks#update', :as => :update_dogs
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
  get '/auth/github/callback' => 'sessions#create'
  get 'dogs/:id/schedule' => 'dogs#schedule', :as => :schedule
  post "dogs/create" => 'dogs#create', :as => :create_dog
  get '/walks/:id/participants' => 'walks#participants', :as => :participants

  match '/login' => 'sessions#new', via: [:get, :post]
  match '/auth/user/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/user/register', to: 'sessions#create', via: [:get, :post]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<% if session[:user_id] %>

    <%= "Currently, Walkeeze's most active dog is:" %>
    <%= "#{Dog.most_walks.name}, with a total of #{Dog.most_walks.dogs_walks.count} walks!" %><br><br>



  <%= "Welcome to Walk-eze #{@user.name}! " %><br><br>


  <p><%= button_to "Go to your Page", user_path(@user), {method: :get} %></p>
  <p><%= button_to "Book a Walk", walks_path, {method: :get} %></p><br>
<% else %>
<%= "Walk-eze - the easiest way to get your dog walked!" %><br><br>


  <%= "Join our most active dog #{Dog.most_walks.name}, who so far has a total of #{Dog.most_walks.dogs_walks.count} walks!" %><br><br>


  <p>
    <strong>Don't use GitHub?</strong><br>
    <%= link_to "Create an account", new_user_path %> or login below.
  </p>

  <%= form_tag "/login" do %>
    <div class="field">
      <%= label_tag :email, "Email" %><br>
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br>
      <%= password_field_tag :password %>
    </div>
    <div class="actions"><%= submit_tag "Login" %></div>
  <% end %>
  <img class="responsive-img" src="cool_pic.jpg">
<% end %>