config/routes.rb
Rails.application.routes.draw do
  resources :dogs, :users, :welcome, :sessions, :walks

  resources :users do
    resources :dogs, :walks
  end

  resources :dogs do
    resources :walks
  end

  # root to: "photos#index"
resources :photos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  patch '/users/:id' => 'user#udpate', :as => :update_user
  get '/update_dogs' => 'walks#update', :as => :update_dogs
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login' => 'sessions#new', :as => :login
  get '/auth/github/callback' => 'sessions#create'
  get 'dogs/:id/schedule' => 'dogs#schedule', :as => :schedule
  post "dogs/create" => 'dogs#create', :as => :create_dog
  get '/walks/:id/participants' => 'walks#participants', :as => :participants

  match '/login' => 'sessions#new', via: [:get, :post]
  match '/auth/user/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/user/register', to: 'sessions#create', via: [:get, :post]
end

app/models/walk.rb
class Walk < ApplicationRecord
  validates :walker_name, :date, :time, :length, :available_spots, presence: true

  has_many :dogs_walks
  has_many :dogs, through: :dogs_walks

  accepts_nested_attributes_for :dogs_walks
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController

  def index
    @walks = Walk.all
  end

  def create
    @walk = Walk.find(params[:id].to_i)
    if params[:dog_ids]
      params[:dog_ids].map(&:to_i).each do |d|
        if !@walk.dogs.ids.include?(d)
          @dog = Dog.find(d)
          @walk.dogs << @dog
        end
      end
    else
      params[:dog_ids]=[]
    end

    @walk.dogs.each do |wd|
      if !params[:dog_ids].map(&:to_i).include?(wd.id)
        if wd.user_id == current_user.id
          @walk.dogs.delete(wd)
        end
      end
    end

    if @walk.dogs.count > @walk.available_spots
      redirect_to edit_walk_url(@walk)
      flash[:notice] = 'There is not enough space for all these dogs! Please choose fewer dogs.'
    else
      @walk.save
      render 'confirm_walk'
    end
  end

  def update
    @dogs_walk_id = DogsWalk.where(dog_id: params[:dog_id].to_i, walk_id: params[:id].to_i)
    @dog_walk = DogsWalk.find(@dogs_walk_id.ids)[0]
    @dog_walk.notes = params[:note]
    @dog_walk.save
    @dog = Dog.find(params[:dog_id])
    render :json => {:dog_walk => @dog_walk, :dog_name=> @dog.name }
  end

  def edit
    @walk = Walk.find(params[:id].to_i)
    @dogs = Dog.where(user_id: @user.id)
  end

  def show
    @walk = Walk.find(params[:id].to_i)
    respond_to do |format|
      format.html
      format.json {render json: @walk, include: [:dogs]}
    end

  end

  # def participants
  #   # @participants = []
  #   @walk = Walk.find(params[:id].to_i)
  #   # @walk.dogs.each do |dog|
  #   #   @participants.push(dog)
  #   # end
  #   render :json => @walk, :include => [:dogs]
  # end

  private

  def walk_params
    params.require(:walk).permit(:name, :length, :available, :available_spots, :date, :time, :notes)
  end

end

app/views/walks/_add_dogs.html.erb
<p>Who's joining the walk?</p>
<%= form_for "walks", :url => {:action => "create", :id => walk.id}  do |f| %>
  <% if dogs %>
    <% dogs.each do |d| %>
      <div>
        <%= check_box_tag "dog_ids[]", d.id, walk.dogs.include?(d) %>
        <%= "#{d.name}  "%><br>
      </div>
    <% end %>
  <% end %>
    <%= f.submit "Submit"%>
<% end %>

app/views/walks/_form.html.erb
<h3> <%= walk.walker_name %>'s Walk </h3>
<p><%= walk.date %> @ <%= walk.time %></p>
<p><%= walk.length %> Mins, <%= (walk.available_spots) - (walk.dogs.count) %> spots available </p>
<p><%= "Notes: " %> <%= walk.notes %></p>

app/views/walks/_show_dogs.html.erb
<% if walk.dogs.count > 0 %>
  <p>The following dogs are booked for this walk!</p>
  <% walk.dogs.each do |d| %>
    <p><%= d.name %></p>
  <% end %>
<% end %>

app/views/walks/_update_dogs.html.erb
<% if walk.dogs.count > 0 %>
  <p>The following dogs are booked for this walk!</p>
  <% walk.dogs.each do |d| %>
    <div class="dog<%=d.id%>"}>
      <% dog_id = d.id %>
      <div class="input-group" align="left" >
        <div class="form-inline">
          <p><%= d.name %>
          <% if d.user.id == current_user[:id] %>
            <%= form_for walk, :html => {class: "dog_note"} do |f| %>
              <%= hidden_field_tag(:dog_id, dog_id) %>
              <%= text_field_tag("note", :note, :size => 15) %>
              <%= button_to 'Add Note', {:action => "update"}, {:method => :patch } %>
            <% end %>
          <% end %>
        </div>
      </div></p>
    </div>
  <% end %>
  <div class="dog_notes">
    Notes

  </div>
<% end %>

app/views/walks/confirm_walk.html.erb
<%= render partial: 'form', locals: { walk: @walk } %><br><br>
<%= render partial: 'update_dogs', locals: { walk: @walk } %><br><br><br><br>


<p><%= button_to "Go to your Page", user_path(current_user.id), {method: :get} %></p>
<p><%= button_to "Edit Your Booking", edit_walk_path(@walk), {method: :get} %></p><br>

app/views/walks/edit.html.erb
<%= render partial: 'form', locals: { walk: @walk } %>

<%= render partial: 'add_dogs', locals: { walk: @walk, dogs: @dogs } %>


<p><%= button_to "Go to your Page", user_path(current_user.id), {method: :get} %></p>

app/views/walks/index.html.erb
<h2>Choose from the following walks</h2>

<% @walks.each do |walk| %>
  <%= render partial: 'form', locals: { user: @user, dog: @dog, dogs: @dogs, walk: walk } %>

  <%= link_to "Show Dogs on this Walk!", walk_path(walk.id), class: "walk_list" %>

  <div class="dog_list<%=walk.id%>"></div>

  <ul>
    <p id="dogs_list<%=walk.id%>">      </p>
  </ul>

  <p><%= button_to "Book This!", edit_walk_path(walk.id), {method: :get} %></p><br>
<% end %>


<p><%= button_to "Go to your Page", user_path(current_user.id), {method: :get} %></p>

app/views/walks/new.html.erb
this is the new walks form - it will be where Walkers add walks

app/views/walks/show.html.erb
<%= render partial: 'form', locals: { walk: @walk } %><br><br>
<%= render partial: 'show_dogs', locals: { walk: @walk } %><br><br><br><br>


<p><%= button_to "Go to your Page", user_path(current_user.id), {method: :get} %></p>
<p><%= button_to "Edit Your Booking", edit_walk_path(@walk), {method: :get} %></p><br>